language: c

sudo: required

before_script:
  - ulimit -r
  - echo "* hard rtprio 2" | sudo tee -a "/etc/security/limits.d/squeak.conf" > /dev/null
  - echo "* soft rtprio 2" | sudo tee -a "/etc/security/limits.d/squeak.conf" > /dev/null
  - sudo su ${USER}
  - ulimit -r

script:
 - ulimit -r
 - false
