language: c

sudo: required

before_script:
  - ulimit -r
  - sudo apt-get install util-linux
  - PID=$$
  - sudo prlimit --pid $PID --rtprio=2:2
  - ulimit -r
  - prlimit --pid $PID --rtprio=2:2
  - ulimit -r

script:
 - ulimit -r
 - false
