language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Squeak-5.1
  - Pharo-6.0
  - GemStone-3.3.0

jobs:
  include:
    - smalltalk_config: a.ston
    - smalltalk_config: b.ston
  
script:
  - echo $TRAVIS_SMALLTALK_VERSION
  - echo $TRAVIS_SMALLTALK_CONFIG
