language: c

sudo: required

before_script:
  - ulimit -r
  - wget https://dl.bintray.com/hpi-swa-lab/smalltalkCI/prlimit
  - chmod +x prlimit
  - PID=$$
  - sudo ./prlimit --pid=$PID --rtprio=2:2
  - ulimit -r

script:
 - ulimit -r
