language: c

sudo: required

before_script:
  - ulimit -r
  - wget https://dl.bintray.com/hpi-swa-lab/smalltalkCI/set_rtprio_limit
  - chmod +x set_rtprio_limit
  - PID=$$
  - sudo ./set_rtprio_limit $PID
  - ulimit -r

script:
 - ulimit -r
